name: my_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.4.0
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  audioplayers: ^5.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
